# Generated by Django 4.2.4 on 2023-09-04 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_alter_comment_pub_date_alter_note_pub_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'verbose_name': 'Ноты', 'verbose_name_plural': 'Ноты'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 4, 13, 12, 22, 657844, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='note',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 4, 13, 12, 22, 657844, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
