# Generated by Django 4.2.4 on 2023-09-04 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_alter_comment_options_alter_note_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 4, 13, 31, 23, 597079, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='note',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 4, 13, 31, 23, 596077, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
