# Generated by Django 4.2.4 on 2023-09-05 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0014_alter_comment_pub_date_alter_note_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='composer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 5, 8, 50, 22, 275527, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='note',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 5, 8, 50, 22, 275527, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
