# Generated by Django 4.2.4 on 2023-09-05 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0015_note_composer_alter_comment_pub_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='pdf',
            field=models.FileField(blank=True, upload_to='books/'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 5, 10, 45, 34, 808418, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='note',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 5, 10, 45, 34, 808418, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
