# Generated by Django 4.2.4 on 2023-09-07 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0028_rename_text_note_description_alter_comment_pub_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 7, 13, 54, 2, 310448, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='note',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 7, 13, 54, 2, 310448, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
