# Generated by Django 4.2.4 on 2023-09-07 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0033_alter_comment_pub_date_alter_note_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 7, 15, 16, 21, 650643, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='note',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 7, 15, 16, 21, 649642, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
