# Generated by Django 4.2.4 on 2023-09-08 12:40

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0037_alter_comment_pub_date_alter_note_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='midi',
            field=models.FileField(blank=True, default=None, null=True, upload_to='midi'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 8, 12, 40, 30, 154389, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='note',
            name='pdf',
            field=models.FileField(blank=True, default=None, null=True, upload_to='pdf/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='note',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 8, 12, 40, 30, 153386, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
