# Generated by Django 4.2.4 on 2023-09-08 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0038_note_midi_alter_comment_pub_date_alter_note_pdf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='midi',
        ),
        migrations.AddField(
            model_name='note',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 8, 12, 55, 53, 466805, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='note',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 8, 12, 55, 53, 466805, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
