# Generated by Django 4.2.4 on 2023-09-08 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0039_remove_note_midi_note_audio_alter_comment_pub_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 8, 16, 9, 2, 74987, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='note',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 8, 16, 9, 2, 73993, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
